comment: 
  layout: "reach, diff, files, footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

coverage:
  precision: 2
  round: down
  range: "70..100"
  
  status:
    project:
      default:
        target: 85
        threshold: 1%
        informational: false
        flags: null
    
    patch:
      default:
        target: 85
        threshold: 5%
        informational: false

flag:
  tests:
    carryforward: true
    paths:
      - tests/

ignore:
  - "man/"
  - "docs/"
